version: '3'
services:
  java:
    build:
      context: .
      dockerfile: java.dockerfile
    image: klilleby/vsts:java-node-9.8
    user: vsts

  node:
    build:
      context: .
      dockerfile: node.dockerfile
    image: klilleby/vsts:node-10.5
    user: vsts

  gcloud:
    build:
      context: .
      dockerfile: gcloud.dockerfile
    image: klilleby/vsts:gcloud-node-10.5
    user: vsts
