version: '3'
services:
  agent1:
    build: 
      context: .
      dockerfile: java.dockerfile
    image: klilleby/vsts:java-node-9.8
    user: vsts

  agent2:
    build: 
      context: .
      dockerfile: node.dockerfile
    image: klilleby/vsts:node-9.8
    user: vsts

